disabled = false
languageCode = "ja"
languageName = "Japanese"
weight = 1
title = "週末螺旋上"

[params]
displayName = "JA"
isoCode = "ja"
rtl = false
dateFormat = "2006 January 2"

["params.author"]
name = "yukidoke"
